Citizen.CreateThread(function()
	-- Makes
	AddTextEntry('LCS', 'LCS')
	AddTextEntry('MODENA', 'Modena')

	-- Models
	AddTextEntry('admiral', 'Admiral')
	AddTextEntry('angel', 'Angel')
	AddTextEntry('apc2', 'APC-2')
	AddTextEntry('blade2', 'Blade')
	AddTextEntry('bobcat', 'Bobcat')
	AddTextEntry('boxville6', 'Boxville')
	AddTextEntry('buccaneer3', 'Buccaneer')
	AddTextEntry('bus2', 'Bus')
	AddTextEntry('cabby', 'Minivan Taxi')
	AddTextEntry('chavos', 'Chavos')
	AddTextEntry('chavos2', 'Chavos Classic')
	AddTextEntry('contender2', 'Contender J')
	AddTextEntry('df8', 'DF8')
	AddTextEntry('diabolus', 'Diabolus')
	AddTextEntry('esperanto', 'Esperanto')
	AddTextEntry('feroci', 'Feroci')
	AddTextEntry('floater', 'Floater')
	AddTextEntry('fortune', 'Fortune')
	AddTextEntry('freeway', 'Freeway')
	AddTextEntry('futo2', 'Futo Stock')
	AddTextEntry('fxt', 'Cavalcade FXT')
	AddTextEntry('hakumai', 'Hakumai')
	AddTextEntry('hellfury', 'Hellfury')
	AddTextEntry('hellion2', 'Hellion Custom')
	AddTextEntry('lokus', 'Lokus')
	AddTextEntry('lycan', 'Lycan')
	AddTextEntry('lycan2', 'Lycan Custom')
	AddTextEntry('marbelle', 'Marbelle')
	AddTextEntry('merit', 'Merit')
	AddTextEntry('mrtasty', 'Mr. Tasty')
	AddTextEntry('nightblade2', 'Nightblade')
	AddTextEntry('nrg900', 'NRG-900')
	AddTextEntry('perennial', 'Perennial')
	AddTextEntry('phoenix2', 'Phoenix RS')
	AddTextEntry('pmp600', 'PMP 600')
	AddTextEntry('premier2', 'Premier Classic')
	AddTextEntry('pres', 'Presidente')
	AddTextEntry('pres2', 'Presidente Custom')
	AddTextEntry('rancher', 'Rancher')
	AddTextEntry('reefer', 'Reefer')
	AddTextEntry('regina2', 'Regina L')
	AddTextEntry('regina3', 'Regina Sedan')
	AddTextEntry('revenant', 'Revenant')
	AddTextEntry('rom', 'Esperanto Roman')
	AddTextEntry('sabre', 'Sabre')
	AddTextEntry('sabre2', 'Sabre (Damaged)')
	AddTextEntry('SCHAFGTR', 'Schafter GTR')
	AddTextEntry('smuggler', 'Smuggler')
	AddTextEntry('solair', 'Solair')
	AddTextEntry('steed', 'Steed')
	AddTextEntry('stratum2', 'Stratum Sedan')
	AddTextEntry('superd2', 'Super Diamond Drop')
	AddTextEntry('taxi2', 'Taxi Merit')
	AddTextEntry('taxi3', 'Taxi Stanier')
	AddTextEntry('tourmav', 'Tour Maverick')
	AddTextEntry('typhoon', 'Typhoon')
	AddTextEntry('uranus', 'Uranus')
	AddTextEntry('vincent', 'Vincent')
	AddTextEntry('violator', 'Violator')
	AddTextEntry('wayfarer', 'Wayfarer')
	AddTextEntry('willard', 'Willard')
	AddTextEntry('wolfsbane2', 'Wolfsbane 2')
	AddTextEntry('yankee', 'Yankee')
end)
