Citizen.CreateThread(function()
	AddTextEntry('7f', '7F')
	AddTextEntry('argento', 'Argento')
	AddTextEntry('ariant', 'Ariant')
	AddTextEntry('arias', 'Arias')
	AddTextEntry('audace', 'Audace')
	AddTextEntry('auroras', 'Aurora Sport')
	AddTextEntry('ballerc', 'Baller Classic')
	AddTextEntry('ASBANSHEE', 'Banshee AS')
	AddTextEntry('BANSHEEPO', 'Banshee Phase One')
	AddTextEntry('barracks4', 'Barracks Flatbed')
	AddTextEntry('bati701', 'Bati 701')
	AddTextEntry('bison4', 'Bison')
	AddTextEntry('blade2', 'Blade')
	AddTextEntry('bspot', 'Everon Stock')
	AddTextEntry('cara', 'Caracara')
	AddTextEntry('chimerac', 'Chimera C')
	AddTextEntry('clique2', 'Clique 2')
	AddTextEntry('cometr', 'Comet Race')
	AddTextEntry('cometrwt', 'Comet Off-Road')
	AddTextEntry('contender3', 'Contender Classic')
	AddTextEntry('coquettecab', 'Coquette Cabrio')
	AddTextEntry('coqvr', 'Coquette VR')
	AddTextEntry('cr250', 'Cr250')
	AddTextEntry('crowdrunner', 'Dominator Crowdrunner')
	AddTextEntry('cycloneex0', 'Cyclone EX-Zero')
	AddTextEntry('cypherct', 'Cypher CT')
	AddTextEntry('dbvolante', 'Massacro Volante')
	AddTextEntry('dloader2', 'Mastodon')
	AddTextEntry('domc', 'Dominator Classic')
	AddTextEntry('DYOSEMITE', 'Yosemite 4x4')
	AddTextEntry('drafterc', 'Drafter Competition')
	AddTextEntry('draftgpr', 'Drafter GPR')
	AddTextEntry('dubstag', 'Dubsta G')
	AddTextEntry('elegant', 'Elegant')
	AddTextEntry('elegyrh6', 'Elegy RH6')
	AddTextEntry('elegysanshi', 'Elegy Sanshi')
	AddTextEntry('elegyw', 'Elegy Wagon')
	AddTextEntry('euphoria', 'Euphoria')
	AddTextEntry('everonb', 'Everon B')
	AddTextEntry('executioner', 'Executioner')
	AddTextEntry('f620d', 'F620 Cabrio')
	AddTextEntry('feltzer4', 'Feltzer V12')
	AddTextEntry('flashrc', 'Flash RC')
	AddTextEntry('furzen', 'Furzen')
	AddTextEntry('fusiladev8', 'Fusilade V8')
	AddTextEntry('gauntletctx', 'Gauntlet CTX')
	AddTextEntry('granger2s', 'Granger 3600LX Custom')
	AddTextEntry('greenwood', 'Greenwood')
	AddTextEntry('greenwood2', 'Greenwood')
	AddTextEntry('howitzer', 'Howitzer')
	AddTextEntry('howler', 'Howler')
	AddTextEntry('huntley2', 'Huntley')
	AddTextEntry('hurricane', 'Hurricane')
	AddTextEntry('infernus4', 'Infernus Cabrio')
	AddTextEntry('italigton', 'Itali GTO-N')
	AddTextEntry('italirsxrod', 'Itali RSX Roadster')
	AddTextEntry('idaho', 'Idaho')
	AddTextEntry('JDORCV12', 'Oracle V12')
	AddTextEntry('JDORCV12A', 'Oracle V12A')
	AddTextEntry('JDORCW', 'Oracle V12W')
	AddTextEntry('JDORCXSW', 'Oracle XS V12W')
	AddTextEntry('JDORCXSV12', 'Oracle XS V12')
	AddTextEntry('jestgpr', 'Jester RR GPR')
	AddTextEntry('kuroi', 'Kuroi')
	AddTextEntry('meteor', 'Meteor')
	AddTextEntry('millennial', 'Millennial Wagon')
	AddTextEntry('mulef', 'Mule F')
	AddTextEntry('muler', 'Mule R')
	AddTextEntry('nexus', 'Nexus')
	AddTextEntry('niner', '9R')
	AddTextEntry('nmule', 'Mule')
	AddTextEntry('nspeedo', 'Speedo Express')
	AddTextEntry('oracxsle', 'Oracle XS LE')
	AddTextEntry('osirisr', 'Osiris R')
	AddTextEntry('pentro', 'Pentro')
	AddTextEntry('pentro3', 'Pentro Cabrio')
	AddTextEntry('pointer01', 'Pointer 01')
	AddTextEntry('premierss', 'Premier SS')
	AddTextEntry('rapidgt4', 'Rapid GT Classic')
	AddTextEntry('razor', 'Razor')
	AddTextEntry('rebel2', 'Rebel')
	AddTextEntry('rebeld', 'Rebel Drift')
	AddTextEntry('recursion', 'Recursion')
	AddTextEntry('remusvert', 'Remusvert')
	AddTextEntry('restovig', 'Vigero VL1 Classic')
	AddTextEntry('revolutions', 'Revolution')
	AddTextEntry('roxanne', 'Roxanne')
	AddTextEntry('rumpoesc', 'Rumpo ESC')
	AddTextEntry('sabrecab', 'Sabre Cabrio')
	AddTextEntry('sadler4', 'Sadler')
	AddTextEntry('sadler9', 'Sadler')
	AddTextEntry('sadlerrt', 'Sadler RT')
	AddTextEntry('sandkingswb', 'Sandking SWB')
	AddTextEntry('savanna', 'Savanna')
	AddTextEntry('scheisser', 'Scheisser')
	AddTextEntry('schnell', 'Schnell')
	AddTextEntry('scout', 'Scout')
	AddTextEntry('sentinels', 'Sentinel S')
	AddTextEntry('sentinelsg4', 'Sentinel S G4')
	AddTextEntry('seraph', 'Seraph')
	AddTextEntry('seraph3', 'Seraph Classic')
	AddTextEntry('seraph10', 'Seraph XS')
	AddTextEntry('severo', 'Severo')
	AddTextEntry('shotaroccc', 'Shotaro C')
	AddTextEntry('sigma3', 'Sigma-Three')
	AddTextEntry('spritzer', 'Spritzer')
	AddTextEntry('spritzerdtm', 'Spritzer DTM')
	AddTextEntry('squaddie3', 'Squaddie')
	AddTextEntry('solairsedan', 'Solair Sedan')
	AddTextEntry('stanier2', 'Stanier')
	AddTextEntry('stardust', 'Stardust')
	AddTextEntry('streiter2', 'Streiter S')
	AddTextEntry('sultanrsv8', 'Sultan RS V8')
	AddTextEntry('sunrise1', 'Sunrise')
	AddTextEntry('supergts', 'Super GTS')
	AddTextEntry('supersanchez', 'Super Sanchez')
	AddTextEntry('surano3', 'Surano GT')
	AddTextEntry('swindler', 'Swindler')
	AddTextEntry('tahoma', 'Tahoma')
	AddTextEntry('terl300', 'Terl 300')
	AddTextEntry('torerod', 'Torero D')
	AddTextEntry('torrence', 'Torrence SSO')
	AddTextEntry('turismowb', 'Turismo WB')
	AddTextEntry('velox', 'Velox')
	AddTextEntry('velox2', 'Velox Custom')
	AddTextEntry('vincent2', 'Vincent Custom')
	AddTextEntry('vincent3', 'Vincent Tourer')
	AddTextEntry('vigero3', 'Vigero R')
	AddTextEntry('vigero4', 'Vigero Custom')
	AddTextEntry('vigeronew', 'Vigero VL1')
	AddTextEntry('voodoo3', 'Voodoo 3')
	AddTextEntry('vorstand', 'Vorstand')
	AddTextEntry('yosemiteswb', 'Yosemite SWB')
	AddTextEntry('zentorno2', 'Zentorno 2')
	AddTextEntry('zion4', 'Zion 4')
	AddTextEntry('zr', 'ZR350 Classic')
	AddTextEntry('ZR390', 'ZR390')
	AddTextEntry('SCHWARTZERCL', 'Schwartzer Classic')
	AddTextEntry('SCHWARTZERC', 'Schwartzer Custom')
	AddTextEntry('SCHWARZER2', 'Schwartzer R')

	AddTextEntry('VIGEROVL1', 'Vigero VL1')
	AddTextEntry('ALAMO', 'Alamo')
	AddTextEntry('alamo2', 'Alamo')
	AddTextEntry('BMX2', 'BMX')
	AddTextEntry('CONTENDERC', 'Contender Custom')
	AddTextEntry('DUBSTA4X4', 'Dubsta 4x4')
	AddTextEntry('ELEGYUTE', 'Elegy UTE')
	AddTextEntry('FUTOPE', 'Futo PE')
	AddTextEntry('NEXUS', 'Nexus')
	AddTextEntry('SCOUT', 'Scout')
	AddTextEntry('savanna', 'Savanna')
	AddTextEntry('yosemiteswb', 'Yosemite SWB')
	AddTextEntry('taranis', 'Taranis')
	AddTextEntry('millennial', 'Millennial Wagon')
	AddTextEntry('PRIMO3', 'Primo LX')
	AddTextEntry('niner', '9R')
	AddTextEntry('VICTOR', 'Victor')

	AddTextEntry('asterope2', 'Asterope RS Classic')
	AddTextEntry('asteropers', 'Asterope RS')

	AddTextEntry('buffalosx', 'Buffalo SX')
	AddTextEntry('buffalo5', 'Buffalo SL')
	AddTextEntry('buffalosl', 'Buffalo SL')
	AddTextEntry('buffaloh', 'Buffalo Hellfire')
	AddTextEntry('gresleyh', 'Gresley Hellfire')
	AddTextEntry('PICADOREXR', 'Picador EXR')
	AddTextEntry('BORDEAUX', 'Bordeaux')
	AddTextEntry('t20gtr', 'T20 GTR')
	AddTextEntry('tempestaes', 'Tempesta ES')
	AddTextEntry('PEACEMKR', 'Peacemaker')
	AddTextEntry('PEACEMKR2', 'Peacemaker')
	AddTextEntry('PEACEMKR3', 'Peacemaker Extended')
	AddTextEntry('celeste', 'Celeste')
	AddTextEntry('hachura', 'Hachura R')

	AddTextEntry('entityxy', 'Entity XY')
	AddTextEntry('thstruck', 'Thunderstruck')
	AddTextEntry('CAVCEXT', 'Cavalcade EXT')
	AddTextEntry('wheelchair', 'Wheelchair')
	AddTextEntry('dominator2', 'Dominator (Racecar)')
    AddTextEntry('TURIWB', 'Turismo Widebody')

	AddTextEntry('gator', 'Gator')
	AddTextEntry('raidenz', 'Raiden Z')
	AddTextEntry('snowmobile', 'Snowmobile')
	AddTextEntry('FLATBED2', 'Flatbed')

	AddTextEntry('ASTER2S', 'Asterope GZ')
	AddTextEntry('AST2SAR', 'Asterope GZ Drift')
	AddTextEntry('MISSILE', 'Hawk Missile')
	AddTextEntry('KART', 'Go-Kart')
	AddTextEntry('KOMODAFR', 'Komoda Custom')
	AddTextEntry('DELUXO6STR', 'Deluxo 6STR')
	AddTextEntry('Wagon','Krusty Krab Mobile')
	AddTextEntry('ZRGPR','ZR350 GPR')
	
	AddTextEntry('HAULMASTER', 'Haulmaster')
	AddTextEntry('HAULER3', 'Hauler Custom')
	AddTextEntry('STURDY3', 'Sturdy')
	AddTextEntry('BARRACKS5', 'Barracks Semi')
	AddTextEntry('BRICKSEM', 'Brickade Semi')
	AddTextEntry('BIFF3', 'Biff Semi')
	AddTextEntry('BMX2', 'BMX Custom')
	AddTextEntry('bmxSt', 'BMX Street')
	AddTextEntry('bmxp2', 'BMX Poland')

	AddTextEntry('CALLISTA', 'Comet Callista')
	AddTextEntry('QUAIL', 'Quail')
	AddTextEntry('italigtoc', 'Itali GTO Custom')
	AddTextEntry('jester3c', 'Jester MK4 Custom')
	AddTextEntry("sentinel6","Sentinel GTS Touring")
	AddTextEntry('egyxven', 'Elegy X Venuum')
	AddTextEntry('hycbansh', 'Banshee Widebody')
	AddTextEntry('brickadeb','Brickade Box Truck')
	AddTextEntry('brickader','Brickade Tow Truck')
	AddTextEntry('brickades','Brickade Semi')
	AddTextEntry("jubven", "Jubilee Venuum")
	AddTextEntry("club8r", "Club 8R")
	AddTextEntry("omsr7", "Omnis SR7")
	AddTextEntry("xlsstr", "XLS STR")
	AddTextEntry("sen5tour", "Sentinel GTS Touring")
	AddTextEntry("sr3", "SR3")
	AddTextEntry("kerosenesr6", "Kerosene SR6")
	
	AddTextEntry('faggios', 'Stretched Faggio Sport')
end)