Citizen.CreateThread(function()
    AddTextEntry('POLBULGT', 'Police Bullet GT')
    AddTextEntry('POLBULGT2', 'Unmarked Bullet GT')
    AddTextEntry('SHERBULGT', 'Sheriff Bullet GT')
    AddTextEntry('HWAYBULGT', 'SAHP Bullet GT')
    AddTextEntry('HWAYBULGT', 'SAHP Bullet GT')
    AddTextEntry('INF2SEPOL', 'Police Infernus Classic')
    AddTextEntry('JACKALLSPD', 'Police Jackal')
    AddTextEntry('POLCHAMP', 'Police Champion')
    AddTextEntry('LSPDRAD', 'Police Radius')
    AddTextEntry('PDRAFTER', 'Police Drafter')
    AddTextEntry('PDRAFTER2', 'Police Drafter 2')
    AddTextEntry('POLICET', 'Burrito Police Transporter')
    AddTextEntry('POLICET2', 'Youga Police Transporter')
    AddTextEntry('POLRAIDEN', 'Police Raiden')
    AddTextEntry('POLSC1', 'Police SC1')
    AddTextEntry('POLTHRUST', 'Police Thrust')
    AddTextEntry('POLTULIP', 'Police Tulip')
    AddTextEntry('POLVACCA', 'Police Vacca')
    AddTextEntry('PSTALKER', 'Unmarked Landstalker XL')
    AddTextEntry('PSADLERK9', 'Police Sadler K9')
    AddTextEntry('PSCOUT', 'Police Scout')
    AddTextEntry('PSCOUTNEW', 'Police Scout Valor')
    AddTextEntry('UMKSCOUT', 'Unmarked Scout')
    AddTextEntry('POLSPEEDO', 'Police Speedo')
    AddTextEntry('POLEVERON', 'Police Everon')
    AddTextEntry('BCSHERIFF', 'BCSO Stanier')
    AddTextEntry('BCSHERIFF2', 'BCSO Granger XL')
    AddTextEntry('GAUNTSHER', 'Sheriff Gauntlet Hellfire')
    AddTextEntry('SHERIFF3', 'Sheriff Interceptor')
    AddTextEntry('SHERIFF4', 'Sheriff Premier')
    AddTextEntry('SHERIFF5', 'Sheriff Esperanto')
    AddTextEntry('POLICE5', 'Police Esperanto')
    AddTextEntry('SHERIFF6', 'Sheriff Rancher')
    AddTextEntry('GRANGERBCSO', 'Sheriff Granger')
    AddTextEntry('LSSDCHAMP', 'Sheriff Champion')
    AddTextEntry('LSSDTULIP', 'Sheriff Tulip')
    AddTextEntry('LSSDTULIP2', 'Sheriff Tulip')
    AddTextEntry('SHERIFFB', 'Sheriff Thrust')
    AddTextEntry('SHERIFFRUMPO', 'Sheriff Rumpo')
    AddTextEntry('SHERIFFSTK', 'Sheriff Landstalker XL')
    AddTextEntry('SHERIFFFUG', 'Sheriff Fugitive')
    AddTextEntry('SHERIFFOSS', 'Sheriff Stanier')
    AddTextEntry('SHERIFFRMR', 'Sheriff Landroamer')
    AddTextEntry('SHERIFFALM', 'Sheriff Alamo')
    AddTextEntry('SHERIFFCQ4', 'Sheriff Coquette')
    AddTextEntry('sherscout', 'Sheriff Scout')
    AddTextEntry('SHRSCT', 'Sheriff Scout')
    AddTextEntry('SHRSCTNEW', 'Sheriff Scout Valor')
    AddTextEntry('FBI3', 'Unmarked Kuruma')
    AddTextEntry('GTFMINIVAN', 'Unmarked Minvan')
    AddTextEntry('NOOSECR', 'BCSO Stanier')
    AddTextEntry('NOOSEPT', 'BCSO Patriot')
    AddTextEntry('POLBCAT', 'Police TARV')
    AddTextEntry('POLICE3A', 'Torrence Police Interceptor')
    AddTextEntry('POLICE3SLICK', 'Torrence Police Interceptor Slick')
    AddTextEntry('POLICEMERIT', 'Police Merit')
    AddTextEntry('POLICE6A', 'Unmarked Merit')
    AddTextEntry('POLICEB', 'Police Sovereign')
    AddTextEntry('POLICEB2', 'Police Hakuchou')
    AddTextEntry('POLMAV2', 'Emergency Maverick')
    AddTextEntry('POLVIGERO', 'Police Vigero R')
    AddTextEntry('PREVOLTER', 'Police Revolter')
    AddTextEntry('RPDCAR5', 'Police Coquette')
    AddTextEntry('SHERIFFGLX', 'Sheriff Granger GLX')
    AddTextEntry('lspdglx', 'Police Granger GLX')
    AddTextEntry('VVPI', 'Blaine County Victor')
    AddTextEntry('VVPI2', 'Blaine County Victor Slick')    
	AddTextEntry('VVPI3', 'Police Victor')
    AddTextEntry('VVPI4', 'Police Victor Slick')	
	AddTextEntry('VVPI5', 'Sheriff Victor')
    AddTextEntry('VVPI6', 'Sheriff Victor Slick')
    AddTextEntry('POLALAMOC', 'PBPD Alamo')
    AddTextEntry('POLALAMOC2', 'PBPD Alamo 2')
    AddTextEntry('POLBISONC', 'PBPD Bison')
    AddTextEntry('POLCARAC', 'PBPD Caracara')
    AddTextEntry('POLFUGITIVEC', 'PBPD Fugitive')
    AddTextEntry('POLGRESLEYC', 'PBPD Gresley')
    AddTextEntry('POLROAMERC', 'PBPD Landroamer')
    AddTextEntry('POLSCOUTC', 'PBPD Scout')
    AddTextEntry('POLSPEEDOC', 'PBPD Speedo')
    AddTextEntry('POLSTALKERC', 'PBPD Landstalker XL')
    AddTextEntry('POLSTANIERC', 'PBPD Stanier')
    AddTextEntry('POLTORENCEC', 'PBPD Torrence')
    AddTextEntry('police3slick', 'PBPD Torrence Slick')
    AddTextEntry('HWAYCAR3', 'SAHP Gresley')
    AddTextEntry('HWAYCARB', 'SAHP Carbonizzare')
    AddTextEntry('hwaycarnew', 'SAHP Interceptor')
    AddTextEntry('HWAYCARSTAN', 'SAHP Stanier')
    AddTextEntry('HWAYFACT', 'SAHP Faction')
    AddTextEntry('GAUNTHWAY', 'SAHP Gauntlet Hellfire')
    AddTextEntry('SAHPB', 'SAHP Sovereign')
    AddTextEntry('SAHPB2', 'SAHP Hakuchou')

    AddTextEntry('polnspeedo', 'Police Speedo Express')
    AddTextEntry('polgreenwd', 'Police Greenwood')
    AddTextEntry('shergreenwd', 'Sheriff Greenwood')
    AddTextEntry('fbigreenwd', 'FIB Greenwood')
    AddTextEntry('as350', 'Police Earthquake')
    AddTextEntry('as365', 'Police Dolphin')
    AddTextEntry('ec-135', 'Police Eagle')
    AddTextEntry('pstanier', 'Police Stanier Classic')
    AddTextEntry('LGUARD', 'Lifeguard Granger')

    AddTextEntry('lsiastan', 'LSIA Police Stanier')
    AddTextEntry('lsiascout', 'LSIA Police Scout')
    AddTextEntry('lsiaalamo', 'LSIA Police Alamo')
    
    AddTextEntry('FBI', 'Unmarked Buffalo')
    
    AddTextEntry('polbufac', 'Police Buffalo A/C')
    AddTextEntry('sherbufac', 'Sheriff Buffalo A/C')
    AddTextEntry('hwaybufac', 'SAHP Buffalo A/C')
    AddTextEntry('fbibufac', 'FIB Buffalo A/C')
    
    AddTextEntry('POLBUFFALOS', 'Police Buffalo S')
    AddTextEntry('BUFFALOLSSD', 'Sheriff Buffalo Hellfire')
    AddTextEntry('HWAYCAR', 'SAHP Buffalo S')
    AddTextEntry('POLBUFFALOC', 'PBPD Buffalo S')
    AddTextEntry('POLICE42OLD', 'Unmarked Buffalo S Retro')

    AddTextEntry('SAHP2STX', 'Police Buffalo SX')
    AddTextEntry('polbufsx', 'Police Buffalo SX')
    AddTextEntry('POLSTX1', 'Police Buffalo SX Slick')
    AddTextEntry('hwaybufsx', 'SAHP Buffalo SX')
    AddTextEntry('hwaybufsx2', 'SAHP Buffalo SX')
    AddTextEntry('POLBUFFALO2', 'PBPD Buffalo SX')
    AddTextEntry('PDUMKSX', 'Unmarked Buffalo SX')
    
    AddTextEntryByHash(0x4CE2D6B4, 'SAHP Thrust')
    AddTextEntryByHash(0x6332126F, 'SAHP Wintergreen')
    AddTextEntryByHash(0xA563A40F, 'SAHP Helicopter')
    AddTextEntryByHash(0xB39170AC, 'SAHP Buffalo A/C')
    AddTextEntryByHash(0xC0F7CE15, 'SAHP Trek')
    AddTextEntryByHash(0xC12AFFD2, 'SAHP Stanier')
    AddTextEntryByHash(0xD0CC6DBE, 'SAHP Scout')
    AddTextEntryByHash(0xDA8C813E, 'SAHP Sandking')
    AddTextEntryByHash(0xE27D9118, 'SAHP Buffalo S')
    AddTextEntryByHash(0xEC162451, 'SAHP Alamo')

    AddTextEntry('POLADDER', 'Police Adder')
    AddTextEntry('POLADDER2', 'Unmarked Adder')
    AddTextEntry('poltgater', 'Unmarked Tailgater')
    AddTextEntry('POLCOMET', 'Police Comet S2')
    AddTextEntry('SAHPCOMET', 'SAHP Comet S2')
    AddTextEntry('sahpgrowler', 'SAHP Growler')
    AddTextEntry('sahpneon', 'SAHP Neon')
    AddTextEntry('polndom', 'Police Dominator GT')
    AddTextEntry('SHERRAIDEN', 'Sheriff Raiden')
    AddTextEntry('LSSDRAFTER', 'Sheriff Drafter')
    AddTextEntry("POLALEUTIAN", "Police Aleutian")
    AddTextEntry('SWATVANR2', 'Police Jogger')
    AddTextEntry('UMKCAVAL3', 'Cavalcade XL Unmarked')
    AddTextEntry('XLS2POLI', 'XLS Unmarked')
    AddTextEntry('NKBUZZARD', 'Police Buzzard')
    AddTextEntry('parawmark', 'Police Paragon X')
    AddTextEntry('polthrax', 'Police Thrax')
    AddTextEntry('pjugular', 'Police Jugular')
end)