Citizen.CreateThread(function()
	AddTextEntry('staffbufs', 'Staff Buffalo S')
	AddTextEntry('staffbufsx', 'Staff Buffalo SX')
	AddTextEntry('staffbufsxuc', 'Staff Buffalo SX')
	AddTextEntry('staffglx', 'Staff Granger GLX')
	AddTextEntry('staffvigr', 'Staff Vigero R')
	AddTextEntry('staffgo4', 'Staff GO-4')
	AddTextEntry('staffcara', 'Staff Caracara')
	AddTextEntry('STAFFCOUCH','Staff Couch')
	AddTextEntry('POTTY','Staff Potty')
	AddTextEntry('staffegt','Staff Omnis e-GT')
	AddTextEntry('STAFFTANK','Staff Tank')
	AddTextEntry('stafflimo', 'Staff Armoured Limousine')
	AddTextEntry('staffrebla', 'Staff Rebla')
	AddTextEntry('testrbufsx', 'Tester Buffalo SX')
	AddTextEntry('bankbuf', 'Gruppe Buffalo')
	AddTextEntry('staffdeluxo', 'Staff Deluxo')
end)
