Citizen.CreateThread(function()
	AddTextEntry('AMBULAN', 'Ambulance')
	AddTextEntry('AMBULAN2', 'Ambulance')
	AddTextEntry('AMBULAN3', 'Ambulance Bison')
	AddTextEntry('AMBULAN4', 'Ambulance Sadler')
	AddTextEntry('AMBULAN22', 'Ambulance Speedo')
	AddTextEntry('emsnspeedo', 'Ambulance Speedo Express')
	AddTextEntry('emsroamer', 'Ambulance Landroamer')
	AddTextEntry('emsannihil', 'Ambulance Annihilator')
	AddTextEntry('steedamb', 'Ambulance Steed')
	AddTextEntry('aemsv450', 'Ambulance V-450')
	AddTextEntry('emsraiden', 'EMS Raiden')
end)
